name: WebScraper CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up GHC
      uses: haskell/actions/setup@v1
      with:
        ghc-version: '9.2.7'

    - name: Install cabal
      run: |
        sudo apt-get update
        sudo apt-get install -y cabal-install

    - name: Update cabal package list
      run: cabal update

    - name: Build
      run: cabal build

    - name: Run
      run: cabal run

