name: WebScraper CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Haskell (GHC + Cabal)
      uses: haskell/actions/setup@v2
      with:
        ghc-version: '9.2.7'
        cabal-version: '3.8.1.0'

    - name: Cache Cabal
      uses: actions/cache@v3
      with:
        path: |
          ~/.cabal/store
          dist-newstyle
        key: ${{ runner.os }}-cabal-${{ hashFiles('**/*.cabal') }}
        restore-keys: |
          ${{ runner.os }}-cabal-

    - name: Update package list
      run: cabal update

    - name: Build dependencies
      run: cabal v2-build all --only-dependencies -j8

    - name: Build project
      run: cabal v2-build -j8

    - name: Run WebScraper
      run: cabal run WebScraper

